name: college_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bottom_navy_bar: ^5.3.2
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.0.11
  shared_preferences: ^0.5.6+3
  line_icons: ^0.1.2
  file_picker: ^1.4.0+1
  flutter_typeahead: ^1.4.0
  firebase_storage: ^3.1.5
  flutter_pdfview: ^1.0.0+9
  path_provider: ^1.6.5
  http: ^0.11.3+15


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.ttf


